// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://azdlkzonmmumelamyyyu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6ZGxrem9ubW11bWVsYW15eXl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNzc0MjYsImV4cCI6MjA2Njg1MzQyNn0.-lg8fiAyg0wKzdiVAeWJeP75l3OL3YTPqdAxiizD8Oo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});